[package]
name = "day12"
version = "0.1.0"
authors = ["felix <felix.hedenstrom@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.1"

[[bin]]
name = "day12"
path = "day12.rs"
